[cnodc.launch.controllers]
"cnodc.dataman.search.DataSearchController" = 1

[cnodc.sources.0.local_test]
search_dir = "hello world"


## Logging settings below
[logging]
version = 1

[logging.root]
level = "INFO"
handlers = ["console"]

[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "brief"
level = "INFO"
stream = "ext://sys.stdout"

[logging.formatters.brief]
format = "%(asctime)s [%(levelname)s] %(message)s"