import dataclasses
import enum
import pathlib
import typing as t
from types import EllipsisType

from medsutil.awaretime import AwareDateTime
from medsutil.exceptions import CodedError
import medsutil.types as ct



class StorageTier(enum.Enum):
    """Storage tiers that generally map to concepts with Azure/Amazon/etc."""

    FREQUENT = "frequent"
    INFREQUENT = "infrequent"
    ARCHIVAL = "archival"
    NA = 'na'


@dataclasses.dataclass
class StatResult:
    st_size: int | None = None
    st_mtime: AwareDateTime | None = None
    metadata: dict[str, str] | None = None
    tier: StorageTier | None = None
    is_dir: bool | None = None
    is_file: bool | None = None
    exists: bool = False


class StorageError(CodedError, OSError): CODE_SPACE = 'STORAGE'


class FeatureFlag(enum.IntFlag):
    METADATA = 1
    TIERING = 2
    FOLDERS = 4
    MODIFIED_TIME = 8
    SIZE = 16
    WALK = 32
    REMOVAL = 64
    CHMOD = 128
    DEFAULT = FOLDERS | MODIFIED_TIME | SIZE | WALK | REMOVAL


class PathType(enum.IntFlag):
    FILE = 1
    DIRECTORY = 2
    BOTH = FILE | DIRECTORY


class FilePath(t.Protocol):
    def __eq__(self, other: FilePath) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: FilePath) -> bool: ...
    def __truediv__(self, other: str) -> t.Self: ...

    @property
    def name(self) -> str: ...

    @property
    def stem(self) -> str: ...

    @property
    def suffixes(self) -> list[str]: ...

    def path(self) -> str: ...

    def stat(self) -> StatResult: ...
    def modified_datetime(self) -> AwareDateTime | None: ...
    def size(self) -> int | None: ...

    def exists(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...

    def with_name(self, name: str, as_dir: bool | None | EllipsisType = ...) -> t.Self: ...
    def with_stem(self, stem: str, as_dir: bool | None | EllipsisType = ...) -> t.Self: ...
    def subdir(self, sub_path: str) -> t.Self: ...
    def subfile(self, sub_path: str) -> t.Self: ...
    def child(self, name: str, as_dir: bool | None = None) -> t.Self: ...
    def joinpath[T](self: T, *args, last_as_dir: bool = False) -> T: ...

    @property
    def parent(self) -> t.Self: ...

    @property
    def parents(self) -> t.Sequence[t.Self]: ...

    @t.overload
    def open(self,
             mode: t.Literal['rb'],
             buffering: t.Optional[int] = None) -> t.ContextManager[ct.SupportsBinaryRead]: ...

    @t.overload
    def open(self, mode: t.Literal['wb']) -> t.ContextManager[ct.SupportsBinaryWrite]: ...

    def open(self,
             mode: t.Literal['rb', 'wb'],
             buffering: t.Optional[int] = None) -> t.ContextManager[ct.SupportsBinaryRead | ct.SupportsBinaryWrite]: ...

    def read_bytes(self) -> bytes: ...
    def write_bytes(self, b: bytes): ...

    def supports_feature(self, ff: FeatureFlag) -> bool: ...

    def download(self,
                 destination: pathlib.Path,
                 allow_overwrite: bool = False,
                 buffer_size: t.Optional[int] = None): ...

    def upload(self,
               source: pathlib.Path | ct.SupportsBinaryRead,
               allow_overwrite: bool = False,
               buffer_size: t.Optional[int] = None,
               metadata: t.Optional[dict[str, str]] = None,
               storage_tier: t.Optional[StorageTier] = None): ...

    def copy(self, destination: FilePath, allow_overwrite: bool = False) -> DestinationType: ...
    def copy_into(self, destination_dir: FilePath, allow_overwrite: bool = False) -> DestinationType: ...

    def move(self, destination: FilePath, allow_overwrite: bool = True) -> DestinationType: ...
    def move_into(self, destination_dir: FilePath, allow_overwrite: bool = True) -> DestinationType: ...
    def rename(self, destination: FilePath) -> DestinationType: ...
    def replace(self, destination: FilePath) -> DestinationType: ...

    def mkdir(self, mode: int = 0o777, parents: bool = True): ...
    def touch(self, mode: int = 0o666): ...

    def remove(self): ...
    def unlink(self): ...
    def rmdir(self): ...

    def chmod(self, mode: int): ...

    def search(self, pattern: t.Optional[str] = None, recursive: bool = True, case_sensitive: bool = False, path_types: PathType = PathType.BOTH) -> t.Iterable[t.Self]: ...
    def iterdir(self, recursive: bool = True, path_types: PathType = PathType.BOTH) -> t.Iterable[t.Self]: ...
    def walk(self) -> t.Iterable[tuple[str, list[str], list[str]]]: ...

    def set_metadata(self, metadata: dict[str, str]): ...
    def get_metadata(self) -> dict[str, str]: ...

    def set_tier(self, tier: StorageTier): ...
    def get_tier(self) -> StorageTier | None: ...




DestinationType = t.TypeVar('DestinationType', bound=FilePath)

