[flask]
UPLOAD_FOLDER = "/service-data/uploads"
MAX_CONTENT_LENGTH = 26214400  # 25 MiB
PERMANENT_SESSION_LIFETIME = 12200  # 2 hour renewal of sessions

[pipeman.service]
config_directory = "/service-config/processes"

[logging]
version = 1

[logging.root]
level = "NOTICE"
handlers = ["console"]

[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "debug"
level = "NOTICE"
stream = "ext://sys.stdout"

[logging.formatters.debug]
format = "%(levelname)s [%(name)s] %(message)s"