import typing as t
import decimal as _decimal

T = t.TypeVar('T')


class NotSupportedMathOperation(ValueError): ...


class Placeholder:
    def __new__(cls):
        return cls


@t.runtime_checkable
class ScienceNumberProtocol[T](t.Protocol):
    @property
    def linear_combo(self) -> LinearCombinationProtocol[T]: ...

    @property
    def units(self) -> str: ...

    @property
    def nominal_value(self) -> T: ...

    @property
    def std_dev(self) -> T | None: ...

    @property
    def num_type(self) -> type[float | _decimal.Decimal]: ...

    def __abs__(self) -> ScienceNumberProtocol[T]: ...

    def __neg__(self) -> ScienceNumberProtocol[T]: ...
    def __pos__(self) -> ScienceNumberProtocol[T]: ...

    def __add__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...
    def __radd__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...

    def __sub__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...
    def __rsub__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...

    def __truediv__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...
    def __rtruediv__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...

    def __mod__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...
    def __rmod__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...

    def __mul__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...
    def __rmul__(self, other: AnyNumber) -> ScienceNumberProtocol[T]: ...

    def __pow__(self, power: AnyNumber, modulo: int | None) -> ScienceNumberProtocol[T]: ...
    def __rpow__(self, base: AnyNumber) -> ScienceNumberProtocol[T]: ...

    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

    def __trunc__(self) -> int: ...

    def __eq__(self, other: AnyNumber) -> bool: ...
    def __ne__(self, other: AnyNumber) -> bool: ...
    def __lt__(self, other: AnyNumber) -> bool: ...
    def __gt__(self, other: AnyNumber) -> bool: ...

    def __hash__(self) -> int: ...

    def match_units(self, other: ScienceNumberProtocol[T]) -> ScienceNumberProtocol[T]: ...

class LinearCombinationProtocol[T](t.Protocol):
    @property
    def linear_combo(self) -> ExpandedLinearCombination[T] | UnexpandedLinearCombination[T]: ...

    def expanded(self) -> ExpandedLinearCombination[T]: ...


def is_science_number(x: t.Any) -> t.TypeGuard[ScienceNumberProtocol]:
    return hasattr(x, 'units') and hasattr(x, 'nominal_value') and hasattr(x, 'std_dev')


type ExpandedLinearCombination = dict[ScienceNumberProtocol, int | float | ScienceNumberProtocol]
type UnexpandedLinearCombination = list[tuple[int | float | ScienceNumberProtocol, LinearCombinationProtocol]]

AnyNumber = _decimal.Decimal | int | float | ScienceNumberProtocol
